@baseUrl = http://localhost:5000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImE2ZWNiYjc5LWQ1YzEtNGJkOS1hOGNiLWNkNTJkNzk3Mzc0NSIsIm5hbWVpZCI6IjMxNjg4NGM2LWQ4YzctNDhiZC05NzZkLTMxZWM3ZjUxYzcwZiIsInJvbGUiOiJNZW1iZXIiLCJuYmYiOjE2ODgyNTIyNjIsImV4cCI6MTY4ODUxMTQ2MiwiaWF0IjoxNjg4MjUyMjYyfQ.KARQXgLAnGAMVMN4JlNk4hq0EGHE_HJC1drP8VEi74w

# Get Hotel List
GET {{baseUrl}}/hotels HTTP/1.1
Authorization: Bearer {{token}}

###

POST {{baseUrl}}/hotels HTTP/1.1
content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Good Hotel",
    "location": "Sylhet",
    "locationOnMap": "https://goo.gl/maps/EyDBMbcJL6mLccbbA"
}