@baseUrl = http://localhost:5000/api

@token = adkadkakdhsaiudhaiudhsaiudhaiuhduahdiuahduahfefe

# Get Hotel List
GET {{baseUrl}}/hotels HTTP/1.1
Authorization: Bearer {{token}}

### Add Hotel

POST {{baseUrl}}/hotels HTTP/1.1
content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Another Hotel 2",
    "location": "Sylhet",
    "locationOnMap": "https://goo.gl/maps/EyDBMbcJL6mLccbbA"
}

### Add Member
POST {{baseUrl}}/account/add-member HTTP/1.1
Content-Type: application/json

{
    "name": "Sirat",
    "email": "s@a.com",
    "password": "11111111",
    "role": "Moderator"
}

### Register
POST {{baseUrl}}/account/register HTTP/1.1
Content-Type: application/json

{
    "name": "Sirat",
    "email": "@@@.com",
    "password": "11111111"
}

### Login
POST {{baseUrl}}/account/login HTTP/1.1
Content-Type: application/json

{
    "name": "Sirat",
    "email": "@@@.com",
    "password": "11111111"
}